# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit vazul_manuscript_jss.Rmd to modify this file

## ----defaults, include=FALSE--------------------------------------------------
library(knitr)

options(prompt = 'R> ', continue = '+ ')


## ----setup, message=FALSE-----------------------------------------------------
library(vazul)
library(dplyr)

set.seed(1037)

data(marp)
data(williams)


## ----mask_labels_example------------------------------------------------------
# Create a simple treatment vector
treatment <- c("control", "treatment_1", "treatment_2", "control", "treatment_1", "treatment_2")

# Mask the labels
mask_labels(treatment)



## ----mask_labels_groups-------------------------------------------------------
mask_labels(treatment, prefix = "group_")


## -----------------------------------------------------------------------------
marp_example <-
    marp |>
    select(subject, country, denomination) |> 
    sample_n(6)

marp_example
    
marp_example |> 
    mask_variables(c("country", "denomination"))

marp_example |> 
    mask_variables(where(is.character))



## -----------------------------------------------------------------------------
df <- data.frame(pre_condition = c("A", "B", "C", "D"),
                 post_condition = c("B", "D", "D", "C"),
                 id = c(1, 2, 3, 4)
                 )
df

mask_variables(df, 
               c("pre_condition", "post_condition"),
               across_variables = TRUE)


## -----------------------------------------------------------------------------
df <- data.frame(id = 1:3,
                 wave_1 = c("control", "treatment_1", "treatment_2"),
                 wave_2 = c("treatment_1", "treatment_2", "control"),
                 wave_3 = c("treatment_2", "control", "treatment_1"),
                 wave_4 = c("treatment_2", "control", "treatment_1")
                 )
df

mask_variables_rowwise(df, starts_with("wave_"))



## -----------------------------------------------------------------------------
names(williams)

williams |> 
    mask_names(starts_with("Impul"), prefix = "masked_") |> 
    names()


## -----------------------------------------------------------------------------
masked_williams <- 
    williams |> 
    mask_names(starts_with("SexUnres"), prefix = "masked_set_A_") |>  
    mask_names(starts_with("Impul"), prefix = "masked_set_B_") |> 
    mask_names(starts_with("Opport"), prefix = "masked_set_C_") |> 
    mask_names(starts_with("InvEdu"), prefix = "masked_set_D_") |> 
    mask_names(starts_with("InvChild"), prefix = "masked_set_E_")

names(masked_williams)


## -----------------------------------------------------------------------------
masked_williams |> 
  select(starts_with("masked_set")) |> 
  factanal(factors = 3, rotation = "varimax") |> 
  loadings() |> 
  print(cutoff = 0.3, sort = TRUE)


## -----------------------------------------------------------------------------
# Numeric data
numbers <- 1:10
scramble_values(numbers)


## -----------------------------------------------------------------------------

williams_example <-
    williams |>
    select(subject, age, ecology) |> 
    head()

williams_example

scramble_variables(williams_example, c("age", "ecology"))



## -----------------------------------------------------------------------------
scramble_variables(williams_example, c("age", "ecology"), together = TRUE)


## -----------------------------------------------------------------------------
df <- data.frame(x = 1:6,
                 y = letters[1:6],
                 group = c("A", "A", "A", "B", "B", "B")
                 )
df 

scramble_variables(df, c("x", "y"), .groups = "group")



## -----------------------------------------------------------------------------
df_wide <- data.frame(
  day_1 = c(1, 4, 7),
  day_2 = c(2, 5, 8),
  day_3 = c(3, 6, 9),
  score_a = c(10, 40, 70),
  score_b = c(20, 50, 80),
  id = 1:3
)

df_wide

scramble_variables_rowwise(df_wide, starts_with("day_"), c("score_a", "score_b"))

